---
  - src: git@github.com:netology-code/mnt-homeworks-ansible.git
    scm: git
    version: "2.0.0"
    name: elastic
  - src: git@github.com:lereklerik/kibana-role.git
    scm: git
    version: "1.0.4"
    name: kibana
  - src: git@github.com:lereklerik/filebeat-role.git
    scm: git
    version: "1.0.7"
    name: filebeat
  - src: git@github.com:lereklerik/logstash-role.git
    scm: git
    version: "1.0.7"
    name: logstash