---
- name: Work with elasticsearch-role
  hosts:
    - el-centos
  roles:
    - elastic
- name: Work with kibana-role
  hosts:
    - k-centos
  roles:
    - kibana
- name: Work with filebeat-role
  hosts:
    - f-centos
  roles:
    - filebeat