---
- name: Work with elasticsearch-role
  hosts:
    - local
  roles:
    - elastic
- name: Work with kibana-role
  hosts:
    - local
  roles:
    - kibana
- name: Work with filebeat-role
  hosts:
    - local
  roles:
    - filebeat